sudo: required
services:
  - docker

before_install:
  - docker build -t zmitja/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run zmitja/react-test npm test -- --coverage

after_success:
  - docker build -t zmitja/multi-client ./client
  - docker build -t zmitja/multi-nginx ./nginx
  - docker build -t zmitja/multi-server ./server
  - docker build -t zmitja/multi-worker ./worker
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker hub
  - docker push zmitja/mutli-client
  - docker push zmitja/mutli-nginx
  - docker push zmitja/mutli-server
  - docker push zmitja/mutli-worker
